//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36388
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;


public enum TYPE_GAMEEND{VICTORY, DEFEAT, DRAW}

public class UIGameEndClass : MonoBehaviour
{
	[SerializeField] GameObject m_victoryPanel;
	[SerializeField] GameObject m_defeatPanel;
	[SerializeField] GameObject m_drawPanel;

	void Awake(){
		m_victoryPanel.SetActive (false);
		m_defeatPanel.SetActive (false);
		m_drawPanel.SetActive (false);
	}


	public void gameEnd(TYPE_GAMEEND gameEnd){
		switch (gameEnd) {
		case TYPE_GAMEEND.VICTORY:
			m_victoryPanel.SetActive (true);
			break;
		case TYPE_GAMEEND.DEFEAT:
			m_defeatPanel.SetActive (true);
			break;
		case TYPE_GAMEEND.DRAW:
			m_drawPanel.SetActive (true);
			break;
		}

		//StartCoroutine (gameEndCoroutine());
	}








}


