//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
public class UIRespawnClass : UIParentClass
{

	[SerializeField] Image m_characterIcon;
	[SerializeField] Image m_weamponIcon;
	[SerializeField] Slider m_slider;
	[SerializeField] Text m_text;
	[SerializeField] Text m_timeText;


	public void setRespawnView(UICharacterClass inflictCharacter, IBullet bullet){


		string color = "gray";
		if (inflictCharacter != null) {
			switch (inflictCharacter.team) {
			case TYPE_TEAM.TEAM_0:
				color = "cyan";
				break;
			case TYPE_TEAM.TEAM_1:
				color = "red";
				break;
			case TYPE_TEAM.TEAM_2:
				color = "lime";
				break;
			case TYPE_TEAM.TEAM_3:
				color = "magenta";
				break;
			}
			m_characterIcon.sprite = inflictCharacter.character.mosData.mosData.characterRound;
			m_weamponIcon.sprite = bullet.weaponSprite;
			m_text.text = string.Format ("<color={0}>{1}</color>의 공격에 사망하였습니다", color, inflictCharacter.nickname);
		} else {
			m_characterIcon.sprite = null;
			m_weamponIcon.sprite = bullet.weaponSprite;
			m_text.text = string.Format ("<color={0}>폭발물</color>에 휘말렸습니다", color);
		}

		gameObject.SetActive (true);
	}

	public void gameUpdate(float respawnTime, float respawnTimeMax){
		m_slider.value = PrepClass.ratioCalculator(respawnTime, respawnTimeMax);
		m_timeText.text = string.Format ("{0:F1}초 후에 부활합니다", respawnTimeMax - respawnTime);

		if(m_slider.value >= 1f) m_parent.gameRestart ();
	}

}


