//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
public class UIReadyEquipmentClass : MonoBehaviour
{

	[SerializeField] UIMOSEquipmentClass[] m_mosEquipments;
	[SerializeField] Toggle m_equipmentToggle; //사용안함 - 차후에 사용

//	int[] m_equipments = new int[3];
	public int[] equipments{
		get
		{
			return new int[] {
				m_mosEquipments [0].equipSlot,
				m_mosEquipments [1].equipSlot,
				m_mosEquipments [2].equipSlot
			};
		}
	}


	/// <summary>
	/// 장비 초기화
	/// </summary>
	/// <param name="mos">Mos.</param>
	public void initEquipment(TYPE_MOS mos){
		foreach (UIMOSEquipmentClass mosEquipment in m_mosEquipments) {
			mosEquipment.initMOS (mos);
		}
	}

}


