//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface IBullet
{
	/// <summary>
	/// 사용하는 캐릭터
	/// </summary>
	/// <value>The character.</value>
	UICharacterClass characterCtrler { get; }

	/// <summary>
	/// 탄환 무기 스프라이트
	/// </summary>
	/// <value>The sprite.</value>
	Sprite weaponSprite{get;}

	/// <summary>
	/// 탄환 타입	
	/// </summary>
	/// <value>The type.</value>
    Type type { get; }

	/// <summary>
	/// 관통 가능 여부
	/// </summary>
	/// <value><c>true</c> 관통 가능 <c>false</c>관통 불가</value>
	bool isPenetrate{ get; set;}
	//TYPE_BULLET_PENETRATE typeBulletPenetrate{ get; set;}

	/// <summary>
	/// 탄환 이펙트 여부
	/// </summary>
	/// <value>The type bullet effect.</value>
//	TYPE_BULLET_EFFECT typeBulletEffect{ get; }


	/// <summary>
	/// 참호 규칙
	/// </summary>
	/// <value><c>true</c> 참호 내 판정 100% 데미지  <c>false</c>참호 외 판정 - 참호 버프시 데미지 반감 </value>
	bool isInTrench{get;}

	/// <summary>
	/// 데미지
	/// </summary>
	/// <value>The damage.</value>
	int damage{ get; set;}
}


