//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public enum TYPE_EQUIPMENT{WEAPON, ARMOR, ACCESSERY}

public abstract class EquipmentClass : MonoBehaviour, IEquipmentInterface, IEquipementPrototypeInterface, ICloneable
{
	string m_contents;

//	BitArray m_mosArray = new BitArray(Enum.GetValues(typeof(TYPE_MOS)).Length);

	[SerializeField] Sprite m_equipIcon; //장비 아이콘
	[SerializeField] Sprite m_equipImage; //장비 이미지
	[SerializeField] string m_key; //장비 키
	[SerializeField] protected string m_name; //이름
//	[SerializeField] string m_nameKey;
	[SerializeField] protected bool[] m_mosArray = new bool[9];
//	[SerializeField] protected TYPE_MOS m_mos;//사용자
	[SerializeField] protected TYPE_EQUIPMENT m_equipType; //장비 타입
	[SerializeField] bool m_isPrice = true; //판매가능
	[SerializeField] BuffDataClass m_option; //옵션

	public string equipName{get{return m_name;}}
//	public string nameKey{get{return m_nameKey;}}
	public bool[] mos{get{return m_mosArray;}}
	public TYPE_EQUIPMENT equipType{get{return m_equipType;}}
	public bool isPrice{ get { return m_isPrice; } }
	public BuffDataClass option{get{return m_option;}}

	public Sprite equipIcon{ get { return m_equipIcon; } }
	public Sprite equipImage{ get { return m_equipImage; } }

	//아이콘
	//이미지
	//스킬데이터

	public object Clone(){
		return (object)this.MemberwiseClone ();
	}

}


