//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
public class TranslatorClass : SingletonClass<TranslatorClass>
{

    Dictionary<string, string> m_mapNameDic = new Dictionary<string, string>();


	public TranslatorClass(){
		initParse ();
	}

	private void initParse(){

		//데이터화 필요
		m_mapNameDic.Add("MP0000", "훈련소");
		m_mapNameDic.Add("MP0100", "오리사 시가전 (소형)");
		m_mapNameDic.Add("MP0101", "오리사 시가전 (중형)");
		m_mapNameDic.Add("MP0102", "오리사 시가전 (대형)");

		//번역기 파싱
		//해당 데이터와 번역기로 출력
		//한글, 영어 등
	}


    /// <summary>
    /// 맵 번역기
    /// </summary>
    /// <param name="mapKey"></param>
    /// <returns></returns>
    public string mapTranslator(string mapKey)
    {
        if (m_mapNameDic.ContainsKey(mapKey))
        {
            return m_mapNameDic[mapKey];
        }
        return "-";
    }


    /// <summary>
    /// 모드 번역기
    /// </summary>
    /// <param name="mode"></param>
    /// <returns></returns>
    public string modeTranslator(TYPE_MODE mode)
    {
        switch (mode)
        {
            case TYPE_MODE.TOTALWAR:
                return "전면전";
            case TYPE_MODE.SIEGE:
                return "공성전";
			case TYPE_MODE.CAPTURE:
                return "점령전";
            case TYPE_MODE.BASE_ATTACK:
                return "공격전";
			case TYPE_MODE.BASE_DEFENCE:
				return "방어전";
        }
        return "-";
    }


	public string panelTranslator(Type typeClass){
		switch (typeClass.ToString()) {
		case "UILobbyPlayClass":
			return "게임플레이";
		case "UILobbyBattleClass":
			return "AI대전";
		case "UILobbyMosClass":
			return "병과";
		case "UILobbyMosInforClass":
			return "병과정보";
		case "UILobbyShopClass":
			return "상점";
		case "UILobbyCampaignClass":
			return "캠페인";		
		case "UILobbyAccountClass":
			return "계정정보";
		}
		return typeClass.ToString();
	}

	public string mosTranslator(TYPE_MOS mos){
		switch (mos) {
		case TYPE_MOS.DUALIST:
			return "결투사";
		case TYPE_MOS.GUARDIAN:
			return "수호기사";
		case TYPE_MOS.FIREBAT:
			return "화염방사병";
		case TYPE_MOS.ASSAULT:
			return "돌격병";
		case TYPE_MOS.HEAVY:
			return "중화기병";
		case TYPE_MOS.SNIPER:
			return "저격병";
		case TYPE_MOS.MAGICIAN:
			return "마법사";
		case TYPE_MOS.CLERIC:
			return "치유사";
		case TYPE_MOS.BUILDER:
			return "건축가";
		}
		return "-";
	}
  


}


