//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ActionObjectClass : ObjectClass
{
	[SerializeField] protected TYPE_TEAM m_team;
	protected int m_health;


	public int health { get { return m_health; } }
	public TYPE_TEAM team{ get { return m_team; } }

	public override void useObject (){}
	
	/// <summary>
	/// 사용중인 오브젝트 해제
	/// </summary>
	public override void releaseObject(){}

	/// <summary>
	/// 오브젝트 파괴
	/// </summary>
//	public virtual void removeObject(){
//		Destroy(gameObject);
//	}



	/// <summary>
	/// 체력 회복
	/// </summary>
	/// <param name="health">Health.</param>
	protected bool addHealth(int health, int maxHealth){
		if (m_health + health > maxHealth) {
			m_health = maxHealth;
			return false;
		} else {
			m_health += health;
			return true;
		}
			
	}


	/// <summary>
	/// 피격
	/// </summary>
	/// <returns>true : 사망</c> otherwise.</returns>
	/// <param name="team">Team.</param>
	/// <param name="damage">Damage.</param>
	protected bool hitAction(int damage){
		m_health -= damage;
		return !(m_health > 0);
	}

	/// <summary>
	/// 피격
	/// </summary>
	/// <returns><c>true</c> 피격됨 <c>false</c> otherwise.</returns>
	/// <param name="team">Team.</param>
	/// <param name="bullet">Bullet.</param>
	public virtual bool hitAction(TYPE_TEAM team, IBullet bullet){
		return false;
	}


//	public bool hitAction(TYPE_TEAM team, IBullet bullet){
//		if (m_team != team) {
//
//			if (hitAction (bullet.damage)) {
//				removeObject (gameObject);
//			}
//			m_characterFrame.setHPBar (m_health, m_maxHealth);
//			if (bullet.isPenetrate)
//				return false;
//			return true;
//		}
//		return false;
//	}

//	public void setAngle(float angle){
//		m_characterFrame = GetComponent<CharacterFrameClass> ();
//		if (m_characterFrame != null) {
//			m_characterFrame.setAngle (angle);
//		} else {
//			transform.eulerAngles = new Vector3 (0f, 0f, angle);
//		}
//	}
}

