//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class CoverBuffDataClass : BuffDataClass
{

	[SerializeField] int m_healthPerSecond;

	protected override void Start(){
		setBuffLoopDelegate (healing);
		base.Start ();
//		startCoroutine (-1f, healing);
	}
	
	public override void buffStart (ICharacterInterface ownerCharacter, ICharacterInterface actCharacter)
	{
		base.buffStart (ownerCharacter, actCharacter);
		addValueState (this);
	}
	
	public override bool buffEnd ()
	{
		returnValueState (this);
		return base.buffEnd ();
	}

	void healing(){
		int healingPoint = (int)((float)m_healthPerSecond * PrepClass.c_timeGap);
		actCharacter.addHealth (healingPoint, ownerCharacter);
	} 
}


