//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class ElasticityBuffDataClass : BuffDataClass
{

//	[SerializeField] float m_time;
	[SerializeField] float m_addTime;

//	void Awake(){
//		buffStateSet(TYPE_BUFF_STATE_ACT.KILL);
//	}
	
	
//	void Start(){
//		startCoroutine (m_time);
//	}
	
	public override void buffStart (ICharacterInterface ownerCharacter, ICharacterInterface setCharacter)
	{
		base.buffStart (ownerCharacter, setCharacter);
		addValueState (this);
	}
	
	public override bool buffEnd ()
	{
		returnValueState(this);
		return base.buffEnd ();
	}

	public override bool buffReplace ()
	{
		initTime ();
		return true;
	}

	public override bool useBuff (ICharacterInterface useActcharacter)
	{
		addTime (m_addTime);
		return true;
	}
}


