//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
public class FightingSpiritBuffDataClass : BuffDataClass
{
	[SerializeField] BuffDataClass m_shieldBuff; //보호막
//	[SerializeField] float m_attackSpeedPercent; //공격속도 퍼센트
//	[SerializeField] float m_moveSpeedPercent; //이속 퍼센트
//	[SerializeField] float m_time;

//	void Awake(){
//		buffStateSet(TYPE_BUFF_STATE.TIME);
//	}
	
	
//	void Start(){
//		//Debug.Log ("Start : " + GetInstanceID());
//		
//		startCoroutine (m_time, null);
//	}
	
	public override void buffStart (ICharacterInterface ownerCharacter, ICharacterInterface actCharacter)
	{
		base.buffStart (ownerCharacter, actCharacter);
		actCharacter.buffAdd(m_shieldBuff, ownerCharacter, actCharacter);
		addValueState (this);
	}
	
	public override bool buffEnd ()
	{
		returnValueState (this);
		BuffDataClass buff = actCharacter.addState.getBuff (m_shieldBuff.GetType ());
		if (buff != null) buff.buffEnd ();
		
		return base.buffEnd ();
	}

	public override bool buffReplace ()
	{
		initTime ();
		return true;
	}
	

}


