//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
public class StrongbodyBuffDataClass : BuffDataClass
{
//	[SerializeField] float m_timeDelay;
	[SerializeField] float m_healingPercent;

//	Coroutine hitCoroutine = null;

	//float m_hitTime = 0f;


//	void Awake(){
//		buffStateSet(TYPE_BUFF_STATE_ACT.HIT);
//	}
	
	
	protected override void Start(){
		setBuffLoopDelegate (strongBodyCoroutine);
		m_isRemove = false;
		base.Start ();

		if (buffParticle != null) {
			buffParticle.Clear ();
			buffParticle.Stop ();
		}
//		startCoroutine (-1f, strongBodyCoroutine);
	}


	public override bool useBuff (ICharacterInterface character, IBullet bullet)
	{


		//피격시 회복 쿨타임
		//5초후회복
//		m_hitTime = m_timeDelay;
		//Debug.Log ("hit Time : " + m_hitTime);

		if (buffParticle != null) {
			buffParticle.Clear ();
			buffParticle.Stop ();
		}

		initTime ();
		return false;
	}

	void strongBodyCoroutine(){
		//0.1초동안 실행
//		if (m_hitTime < 0f) {
		if (m_runTime >= m_maxTime){
			if (buffParticle != null) {
				if (!buffParticle.isPlaying) {
					soundPlayer.audioPlay (TYPE_SOUND.EFFECT);
					buffParticle.Play ();
				}
			}
			actCharacter.addHealth ((int)((float)actCharacter.maxHealth * m_healingPercent * PrepClass.c_timeGap), ownerCharacter);
		}
//		} else {
//			m_hitTime -= PrepClass.c_timeGap;
//		}
	}

}


