//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class TelescopesightBuffDataClass : BuffDataClass
{
//	void Awake(){
//		buffStateSet(TYPE_BUFF_STATE.CONTINUE);
//	}
	
	
//	void Start(){
//		//Debug.Log ("Start : " + GetInstanceID());
//		startCoroutine (-1f, null);
//	}
	
//	public override void buffStart (ICharacterInterface ownerCharacter, ICharacterInterface actCharacter)
//	{
//		base.buffStart (ownerCharacter, actCharacter);
//	}
//	
//	public override bool buffEnd ()
//	{
//		return base.buffEnd ();
//	}


	public override bool useBuff (ICharacterInterface useActcharacter)
	{
		if (soundPlayer != null)
			soundPlayer.audioPlay (TYPE_SOUND.EFFECT);
		
		return true;
	}

}


