//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class BuilderSkill2Class : SkillClass, ISkillMOSInterface
{

//	[SerializeField] 버프
//	[SerializeField] float m_time;
//	[SerializeField] float m_rate;

	[SerializeField] BuildingObjectClass m_building;

//	public override void initSkill (ICharacterInterface player){
//		//player.buffAdd (m_buff);
//	}

	public override bool skillAction(ICharacterInterface player){
		setParticle (player.transform.position, player.transform);

		BuildingObjectClass building = (BuildingObjectClass)Instantiate (m_building, player.transform.position, new Quaternion ());
		building.initBuilding (player.characterCtrler, player.angle);
		building.initWeaponSprite (iconRound);

//		BuildingManagerBuffDataClass buildingManager = (BuildingManagerBuffDataClass)player.addState.getBuff (typeof(BuildingManagerBuffDataClass));
//		if (buildingManager != null) {
//			buildingManager.addBuilding (building);
//		}
		return base.skillAction (player);
	}

}


